---
  title-block-banner: false
  format:
    html:
      toc: false
  editor: visual
  markdown: 
  editor_options: 
  chunk_output_type: console
  back-to-top-navigation: true
---

## About Us

Details about the DSDE group as a whole.

## Things We Do

Our Data Enclave and Navigation platform is designed to empower YSPH students, staff, and faculty by providing a centralized resource for accessing data and data tools.

**Comprehensive Data Enclave and Navigation Tool:** Access a robust collection of resources designed to support your public health data projects, including resource sites for commonly used public health datasets with information about how to access the data, anticipated timelines for accessing and utilizes these different datasets, and example Yale studies that have been conducted and published using each of these specific datasets.

**Public Health Data Resources:** Discover curated Yale resources such as aggregations of data or computational resources that students, staff and faculty can use in their research.

Brief statement about other things happeneing with DSDE, maybe also point to the Mukherjee lab site too? [Resources](https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/resources/) and [Services](https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/services/).

## People

List of people who are from DSDE and collaborators working on the Resource Navigation Tool.

Link to the whole team here: [People](https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/people/)
