---
title-block-banner: true
title: |
  Beyond the Collection: Faculty Data</br>Applications & Resources
include-in-header: ../../../_includes/feedback_popup.html
toc-depth: 2
bibliography: BibTeX/oaic.bib
csl: ../../../Code/nature.csl
---

```{r}
#| echo: false

# Load in the functions.
source('../../../Code/PubMed Search_Functions.R')
```

<small>Updated: March 4<sup>th</sup>, 2026</small>

## Overview

This page showcases additional data applications and harmonization efforts from Yale University faculty. We hope these examples will inspire new research pathways within the research community and help broaden awareness of valuable resources beyond those in our actively curated collection. To learn more about any dataset or resource listed here, we encourage you to contact the primary investigator noted in the publication.

## Listing

### Medical Expenditure Panel Survey (MEPS) with NAVLIN

**Publication:** [Estimating US savings on outpatient prescription pharmaceuticals from international reference pricing](https://www.pnas.org/doi/10.1073/pnas.2520871122) by Ye et al. 2025

**Abstract:** The exorbitant cost of prescription pharmaceuticals is a critical and long-standing concern facing the United States (US). To curb rising drug costs, international reference pricing, aligning drug prices with those in other high-income countries, has emerged as a prominent policy option. We evaluated the potential national savings from such a strategy in the United States through a comprehensive analysis of utilization patterns and global price differentials for over 8,000 drugs. We project an annual national saving of $184 billion if outpatient prescription pharmaceuticals were priced comparably to those in Canada, France, Germany, Japan, and the United Kingdom. Private insurers, Medicare, and Medicaid would realize savings of 51%, 62%, and 35%, respectively. Pharmaceutical expenditures for common chronic illnesses would be substantially reduced, with costs declining by over 75% for diabetes, atrial fibrillation, and heart failure. Our findings emphasize the substantial fiscal and equity gains achievable through international reference pricing, demonstrating its potential to mitigate financial burdens borne by both healthcare systems and individual patients.

**Dashboard:** [https://irp.cidma.us/](https://irp.cidma.us/)

## Gaining Access

This page highlights data applications and harmonization research shared by Yale researchers. Some of these datasets may already be featured with full access and usage details on our [Datasets](../../datasets.qmd) page. Yale affiliates can submit suggestions by accessing the Qualtrics link in the feedback form at the top.
